#include<iostream>
using namespace std;
main()
{
float num1;
float num2;
float num3;
float num4;
float num5;
float num6;
float num7;
float num8;
float num9;
float num10;
float num11;
float num12;
float num13;
float num14;
float num15;
float first5sum;
float next5product;
float next5subt;
float total;
cout<< "Enter 1st number ";
cin>>num1;
cout<< "Enter 2nd number ";
cin>>num2;
cout<< "Enter 3rd number ";
cin>>num3;
cout<< "Enter 4th number ";
cin>>num4;
cout<< "Enter 5th number ";
cin>>num5;
cout<< "Enter 6th number ";
cin>>num6;
cout<< "Enter 7th number ";
cin>>num7;
cout<< "Enter 8th number ";
cin>>num8;
cout<< "Enter 9th number ";
cin>>num9;
cout<< "Enter 10th number ";
cin>>num10;
cout<< "Enter 11th number ";
cin>>num11;
cout<< "Enter 12th number ";
cin>>num12;
cout<< "Enter 13th number ";
cin>>num13;
cout<< "Enter 14th number ";
cin>>num14;
cout<< "Enter 15th number ";
cin>>num15;
cout<<endl;
first5sum=num1 + num2 + num3 + num4 + num5;
next5product= num6 * num7 * num8 * num9 * num10;
next5subt= num11 - num12 - num13 - num14 - num15;
total= (first5sum+next5product)-next5subt;
cout<< "Total: " <<total;
}